#ifndef __CONSTANTES_MENU_H__
#define __CONSTANTES_MENU_H__

#define MAX_COMPONENTES_MENU 4
#define MAX_COLORES 4
#define RANGO_COLORES 255
#define VALOR_PREDETERMINADO_COLOR 256

#define TAM_INICIAL_BUFFER 1
#define AJUSTE_TAM_BUFFER 2

#define FORMATO_LECTURA_HOTKEY " %c"
#define FORMATO_IMPRESION_COLOR "\033[38;5;%zum"
#define FORMATO_IMPRESION_OPCION "%s [%c]\n\033[0m"
#define FORMATO_IMPRESION_OPCION_ENTER "%s [%s]\n\033[0m"
#define FORMATO_IMPRESION_MARCADOR "%s\033[0m "
#define FORMATO_IMPRESION_TITULO "%s\n\n\033[0m"
#define FORMATO_IMPRESION_MENSAJE_DE_OPCION "\n%s \033[0m"
#define FORMATO_IMPRESION_PROPUESTA_INGRESO_DE_CADENA "%s \033[0m"

#endif // __CONSTANTES_MENU_H__