#ifndef __DICCIONARIO_CONSTANTES_H__
#define __DICCIONARIO_CONSTANTES_H__

#define OCURRIO_REEMPLAZO 1
#define NO_HAY_DUPLICADO 0
#define SIN_ERRORES 0
#define ERROR_MEMORIA -1

#define SEMILLA_HASH 5381
#define FACTOR_AMPLIFICACION_HASH 33
#define CAPACIDAD_MINIMA 3
#define LIMITE_FACTOR_DE_CARGA 0.75
#define FACTOR_ESCALA_CAPACIDAD 2

#endif /* __DICCIONARIO_CONSTANTES_H__ */